---
name: hpffp
version: 0.1.0.0
synopsis: My solutions to Haskell Programming from First Principles
author: Russell Teabeault
maintainer: rteabeault@gmail.com
github: rteabeault/hpffp
build-type: Simple
extra-source-files: README.md

library:
  source-dirs: 
    - src
  dependencies:
    - base >= 4.7 && < 5
    - time
    - QuickCheck >= 2.9
    - checkers
    - containers
    - random
    - transformers
    - mtl
    - dlist
    - trifecta
    - parsers
    - scotty
    - text
    - criterion
    - vector
    - primitive
    - bytestring
    - zlib
    - utf8-string

tests:
  spec:
    main: Spec.hs
    source-dirs: 
      - test
    dependencies:
      - base
      - hpffp
      - QuickCheck
      - checkers
    ghc-options: -threaded -rtsopts -with-rtsopts=-N